all:
	gcc server.c -o server
	gcc hunter.c -o hunter
	gcc prey.c   -o prey
debug:
	gcc server.c -o server -g -Wall -Wextra
	gcc hunter.c -o hunter -g -Wall -Wextra
	gcc prey.c   -o prey -g -Wall -Wextra
clean:
	rm server
	rm hunter
	rm prey
