rasterizer_cpp:
	g++ -o rasterizer hw2_math_ops.cpp hw2_file_ops.cpp rasterizer.cpp hw2_types.cpp -std=c++17
warnings:
	g++ -o rasterizer hw2_math_ops.cpp hw2_file_ops.cpp rasterizer.cpp hw2_types.cpp -Wall -Wextra -std=c++17
clean:
	rm -rf *.ppm *.png ./rasterizer

